description: '"GPT-4o-mini Chatbot Configuration and Test with Prompts"'

prompts:
  - prompt.yaml
providers:
  - openai:chat:gpt-4o-mini

tests:
  - vars:
      content: hey
  - vars:
      content: what can you help with?
  - vars:
      content: tell me about hawaii
