description: 'Example of GPT-4o-mini chatbot test configuration'

prompts:
  - prompt.yaml
providers:
  - openai:chat:gpt-4o-mini

tests:
  - vars:
      content: hey
  - vars:
      content: what can you help with?
  - vars:
      content: tell me about hawaii
