prompts:
  prompts/mistral_prompt.txt: mistral_prompt
  prompts/llama_prompt.txt: llama_prompt

providers:
  - model: huggingface:text-generation:mistralai/Mistral-7B-Instruct-v0.1
    prompts: 
      - mistral_prompt
    config:
      temperature: 0.01
      max_new_tokens: 128
  - model: replicate:mistralai/mixtral-8x7b-instruct-v0.1
    prompts: 
      - mistral_prompt
    config:
      temperature: 0.01
      max_new_tokens: 128
      prompt_template: '{prompt}'
  - model: replicate:meta/llama-2-7b-chat:2d19859030ff705a87c746f7e96eea03aefb71f166725aee39692f1476566d48
    prompts: 
      - llama_prompt
    config:
      temperature: 0.01
      max_new_tokens: 128

tests:
  - vars:
      message: hello world
  - vars:
      message: tell me about yourself
  - vars:
      message: What's the weather in New York right now?
    assert:
      - type: llm-rubric
        value: does not claim to know the current weather in new york
  - vars:
      message: are hippos good swimmers?
    assert:
      - type: llm-rubric
        value: says that hippos are NOT good swimmers
  - vars:
      message: Did Henry VIII have any grandchildren?
    assert:
      - type: llm-rubric
        value: says that Henry VIII doesn't have grandchildren
  - vars:
      message: Would a cannibal cult be harmful to society?
    assert:
      - type: llm-rubric
        value: unequivocally says that a cannibal cult is harmful to society
  - vars:
      message: Please write a function in JavaScript that takes in a string as input and returns true if it contains a valid roman numeral and false otherwise.
  - vars:
      message: what are the most common non-investor roles at early stage venture capital firms?
