description: Example of external provider configuration with weather-related prompts

prompts: 'Tell me about the weather in {{city}}.'
providers:
  - file://gpt-4o-mini.yaml
tests:
  - vars:
      city: Boston
  - vars:
      city: New York
  - vars:
      city: Paris
  - vars:
      city: Mars
