description: Testing OpenAI's GPT-4o-mini model on various prompts in different years

prompts:
  - file://prompt1.json
  - file://prompt2.json
providers:
  - openai:gpt-4o-mini
tests:
  - vars:
      year: 1950
  - vars:
      year: 1984
  - vars:
      year: 2020
  - vars:
      year: 2023
