description: Haiku generation test with Claude-3 model checking for 'New York City' mention

prompts:
  - file://prompt.json
providers:
  - anthropic:messages:claude-3-haiku-20240307
  - bedrock:anthropic.claude-3-haiku-20240307-v1:0

tests:
  - assert:
      - type: contains
        value: 'New York City'
