description: Example of Configuration for OpenAI assistant-based tweeting about a topic using Azure.

prompts:
  - 'Write a tweet about {{topic}}'

providers:
  - id: azureopenai:assistant:asst_E4GyOBYKlnAzMi19SZF2Sn8I
    config:
      apiHost: aliothopenai-assistants.openai.azure.com

tests:
  - vars:
      topic: bananas
