description: 'Example of factuality and closed QA evaluation using OpenAI'

prompts:
  - file://prompts/name_capitals_concise.txt
  - file://prompts/name_capitals_verbose.txt
providers:
  - openai:gpt-4o-mini
tests:
  - vars:
      location: Sacramento

    assert:
      # Ensure the answer agrees with the provided facts
      - type: factuality
        value: The capital of California is Sacramento

      # Ensure the answer meets the criteria
      - type: model-graded-closedqa
        value: Does not include any extra information or facts about Sacramento
