# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Local Websocket Conversation Example
targets:
  - id: websocket
    label: promptfoo-redpanda-websocket-proxy
    config:
      type: websocket
      url: ws://localhost:4000
      messageTemplate: '{"prompt": "{{prompt}}", "sessionId": "{{sessionId}}"}'
      transformResponse: |-
        if (!data || typeof data !== 'object') {
          return { output: 'Invalid response data', history: [] };
        }

        // Return an object with both output and history
        const result = {
          output: data.output || (data.error && `Error: ${data.error}`) || 'No output found',
          history: data.history || []
        };
        return result;
      timeoutMs: 30000
prompts:
  - '{{prompt}}'
redteam:
  purpose: ''
  plugins:
    - id: harmbench # Tests for harmful content using the HarmBench dataset
  strategies:
    - id: basic # Original plugin tests without any additional strategies or optimizations
defaultTest:
  options:
    transformVars: '{ ...vars, sessionId: context.uuid }'
