prompts:
  - "Write a tweet about {{topic}}"

providers:
  - model: cohere:command
    config:
      temperature: 0.5
      prompt_truncation: AUTO
      connectors:
        - model: web-search
      showSearchQueries: true

tests:
  - vars:
      topic: the person who discovered gravity
