# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
prompts:
  - 'Write a very concise funny tweet about {{topic}}'

providers:
  - id: file://provider.py # defaults to call_api function
    config:
      someOption: foobar

tests:
  - vars:
      topic: bananas
    assert:
      - type: contains
        value: Bananamax
  - vars:
      topic: fruits
    assert:
      - type: llm-rubric
        value: includes at least one emoji
  - vars:
      topic: turtles
    assert:
      - type: llm-rubric
        value: is funny
