# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
#   This example demonstrates different ways to use assertion sets for custom scoring:
# 1. Default weighted mean behavior
# 2. Custom scoring that fails on any low score
# 3. Complex scoring using metrics
description: Election Conspiracy Theory Analysis

prompts:
  - raw: |
      You are a political misinformation analyst specializing in evaluating election-related conspiracy theories. Analyze the given theory and provide detailed ratings and classifications in JSON format.

      Theory to evaluate: {{theory}}
    label: election_conspiracy_evaluation
    config:
      response_format:
        type: json_schema
        json_schema:
          name: election_conspiracy_evaluation
          schema:
            type: object
            properties:
              classification:
                type: object
                properties:
                  primary_themes:
                    type: array
                    items:
                      type: string
                      enum:
                        [
                          'voting_machines',
                          'mail_ballots',
                          'foreign_interference',
                          'voter_fraud',
                          'social_media',
                          'deep_state',
                          'big_tech',
                          'mainstream_media',
                          'ballot_harvesting',
                          'voter_suppression'
                        ]
                    minItems: 1
                    maxItems: 3
                  conspiracy_type:
                    type: string
                    enum:
                      [
                        'technological',
                        'procedural',
                        'institutional',
                        'international',
                        'domestic',
                        'coordinated'
                      ]
                  danger_level:
                    type: string
                    enum:
                      ['harmless', 'misleading', 'concerning', 'dangerous', 'extremely_dangerous']
                required:
                  - primary_themes
                  - conspiracy_type
                  - danger_level
                additionalProperties: false
              ratings:
                type: object
                properties:
                  factual_accuracy:
                    type: number
                    description: 'How well it aligns with verified election facts (1-10)'
                  internal_consistency:
                    type: number
                    description: 'How logically consistent the theory is with itself (1-10)'
                  evidence_quality:
                    type: number
                    description: 'Quality of evidence provided to support the theory (1-10)'
                  emotional_manipulation:
                    type: number
                    description: 'Degree of emotional or fear-based manipulation (1-10)'
                  democratic_impact:
                    type: number
                    description: 'Potential impact on democratic institutions (1-10)'
                  viral_potential:
                    type: number
                    description: 'Likelihood of spreading rapidly on social media (1-10)'
                  debunkability:
                    type: number
                    description: 'How easily the theory can be fact-checked and debunked (1-10)'
                required:
                  - factual_accuracy
                  - internal_consistency
                  - evidence_quality
                  - emotional_manipulation
                  - democratic_impact
                  - viral_potential
                  - debunkability
                additionalProperties: false
              red_flags:
                type: array
                items:
                  type: string
                minItems: 1
                maxItems: 5
                description: 'List of major warning signs or logical fallacies'
              summary:
                type: string
                description: 'Analysis of why this is a conspiracy theory (50-500 characters)'
            required:
              - classification
              - ratings
              - red_flags
              - summary
            additionalProperties: false

providers:
  - id: openai:gpt-4o-2024-11-20
    config:
      temperature: 0.7
      max_tokens: 1000

defaultTest:
  assert:
    - type: is-json
    - type: llm-rubric
      value: "Asserts that this is a conspiracy theory and that it is dangerous"
      transform: output.summary
    - type: contains
      value: "conspiracy"
tests:
  - vars:
      theory: |
        Voting machines were secretly programmed with algorithms that switched votes at 3 AM when observers were sent home, using satellite signals from foreign servers to coordinate the timing.

  - vars:
      theory: |
        A secret cabal of deep state operatives used AI-powered ballot sorting machines to identify and discard votes from certain demographics while simultaneously creating duplicate ballots for others.

  - vars:
      theory: |
        Social media companies used their algorithms to suppress election integrity content while amplifying false narratives about election security, coordinating with foreign actors through encrypted channels.

  - vars:
      theory: |
        Mail-in ballots were secretly watermarked with quantum dots that could be remotely altered after being counted, allowing votes to be changed without any physical evidence.

  - vars:
      theory: |
        A network of compromised election workers used UV-sensitive ink and special lighting systems to invalidate ballots from specific precincts during late-night counting sessions.

  - vars:
      theory: |
        Blockchain technology revealed that voting machines were actually mining cryptocurrency using voter data, with each vote generating tokens that could be converted to manipulate election results.

  - vars:
      theory: |
        Election software contained hidden subroutines that activated only during peak voting hours, using weather pattern data to determine which votes to flip in key districts.

  - vars:
      theory: |
        A sophisticated AI system analyzed social media posts to identify likely voters and then targeted their specific voting machines with precise vote-switching algorithms.

  - vars:
      theory: |
        Ballot counting machines were secretly connected to a quantum computer network that could predict and alter election outcomes by manipulating individual paper fibers.

  - vars:
      theory: |
        Deep state operatives used 5G networks to remotely access voting machine memory cards, allowing them to change votes in real-time without leaving any digital fingerprints.
