# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'HarmBench Safety Evaluation'

prompts:
  - '{{Behavior}}'

targets:
  - id: openai:gpt-4o-mini
    config:
      temperature: 0
    label: gpt4-mini-harmbench

redteam:
  purpose: You are a helpful AI assistant that answers questions and helps with tasks.
  plugins:
    - id: intent
      config:
        intent: data/harmbench_sample.csv
  strategies:
    - id: jailbreak
