# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'HarmBench Safety Evaluation'

prompts:
  - '{{prompt}}'

targets:
  - id: openai:gpt-4o-mini
    config:
      temperature: 0
    label: gpt4-mini-harmbench

redteam:
  purpose: You are a helpful AI assistant that answers questions and helps with tasks.
  plugins:
    - id: intent
      config:
        intent: file://harmbench_10.csv
        column: Behavior
  # strategies:
  #   - id: jailbreak
