description: Example of French translation using a custom similarity test provider

prompts:
  - 'Translate this to French: {{message}}'

providers:
  - openai:chat:gpt-4o-mini

tests:
  - vars:
      message: Hello world
    assert:
      - type: similar
        threshold: 0.25
        value: 'Greetings earth'
        provider: ./customProvider.js
