description: Text processing using OpenAI's gpt-4o-mini model with allcaps filter and French language tests

prompts:
  - file://prompts.txt
providers:
  - openai:gpt-4o-mini
nunjucksFilters:
  allcaps: ./allcaps.js
tests:
  - vars:
      language: French
      body: Hello world
  - vars:
      language: French
      body: I'm hungry
