description: Example of Tweet generation using Google's Gemini-Pro provider

prompts:
  - 'Write a tweet about {{topic}}'
  - 'Write a very concise, funny tweet about {{topic}}'

providers:
  - id: google:gemini-pro
    config:
      generationConfig:
        temperature: 0
        topP: 1

tests:
  - vars:
      topic: bananas
