name: PyPI Release
run-name: PyPI Release for ${{ github.ref_name }} by @${{ github.actor }}

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build package
        run: poetry build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-pypi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Download Nexe artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: promptfoo-*
          path: nexe-binaries/
          merge-multiple: true
      - name: Publish to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry config pypi-token.pypi $PYPI_PASSWORD
          poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD