name: PyPI Release
run-name: PyPI Release for ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_run:
    workflows: ['Nexe Build']
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Get package version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(poetry version --short)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Download the Nexe artifact for the current OS
      - name: Download Nexe Artifact
        uses: actions/download-artifact@v4
        with:
          name: promptfoo-${{ matrix.os_short }}-*
          path: nexe_binaries

      - name: Prepare Package
        run: |
          mkdir -p src/promptfoo/binaries/${{ matrix.os_short }}-${{ matrix.arch }}
          mv nexe_binaries/* src/promptfoo/binaries/${{ matrix.os_short }}-${{ matrix.arch }}/promptfoo${{ matrix.ext }}
          ls -l src/promptfoo/binaries/${{ matrix.os_short }}-${{ matrix.arch }}

      - name: Verify Git Tag
        run: |
          git fetch --tags
          TAG_EXISTS=$(git tag -l "v${{ steps.get_version.outputs.version }}" | wc -l)
          if [ "$TAG_EXISTS" -eq "0" ]; then
            echo "Git tag v${{ steps.get_version.outputs.version }} does not exist. Exiting."
            exit 1
          fi
      - name: Build Platform-specific Wheel
        run: poetry build -f wheel
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --skip-existing --username __token__ --password $PYPI_TOKEN
