name: PyPI Release
run-name: PyPI Release for ${{ github.event.workflow_run.head_branch }} by @${{ github.actor }}

on:
  workflow_run:
    workflows: ['nexe build']
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to release'
        required: true

jobs:
  publish-pypi:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Download Nexe artifacts
        uses: actions/download-artifact@v4
        with:
          workflow: nexe-build.yml
          workflow_conclusion: success
          path: nexe-binaries
      - name: Prepare package
        run: |
          mkdir -p src/promptfoo/bin
          mv nexe-binaries/*/* src/promptfoo/bin/
      - name: Build package
        run: poetry build
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }} 
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
